# Generated by Django 3.0.3 on 2026-05-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('status', models.CharField(choices=[('profitable', 'выгодный'), ('doubtful', 'сомнительно'), ('unprofitable', 'невыгодно')], default='doubtful', max_length=15)),
                ('buy_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('url', models.URLField()),
                ('sell_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('comments', models.TextField()),
                ('source_sell', models.URLField()),
                ('source_buy', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
