# Generated by Django 3.0.3 on 2026-05-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_value',
            field=models.IntegerField(default=0),
        ),
    ]
